"""check for pending

Revision ID: 9b09208e4091
Revises: d8ec6c7cd80a
Create Date: 2025-04-18 14:47:04.893527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b09208e4091'
down_revision: Union[str, None] = 'd8ec6c7cd80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'daily_report', ['date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_report', type_='unique')
    # ### end Alembic commands ###
